[package]
name = "kore-net"
description = "Network tools for Kore: HTTP, WebSocket, DNS"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kore.workspace = true
kore-std.workspace = true
tokio.workspace = true
reqwest.workspace = true
tokio-tungstenite.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
indexmap.workspace = true
url = "2"
futures-util = "0.3"

[dev-dependencies]
wiremock = "0.6"
